language: node_js
node_js:
    - "0.8"
    - "0.10"
before_install:
    - sudo add-apt-repository --yes ppa:bitcoin/bitcoin
    - sudo apt-get update
    - sudo apt-get install bitcoind
after_install:
  - git submodule update --init
    
